site_name: SOAR
# site_url: Set this later when deploying to GitHub Pages
repo_url: https://github.com/ripandy/SOAR # <-- Add your repo URL here
repo_name: SOAR # <-- Add your repo name here (e.g., user/repo)
  # You can also use a FontAwesome icon for the repo link:
  # icon:
  #  repo: fontawesome/brands/github

copyright: 'Copyright &copy; 2025 Ripandy Adha'

theme:
  name: material
  favicon: assets/icons/SOAR_icon64.png
  logo: assets/icons/SOAR_icon.png

  features: # Add features section for things like navigation.tabs
    # - navigation.tabs # Uncomment if you want top-level navigation as tabs
    - content.code.copy
    - content.code.select
  
  font:
    text: 'Lato'
    code: 'Fira Code'
    
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Overview: index.md
  - Features: features.md
  - Getting Started:
    - Quick Start: getting-started/quick-start.md
    - Installation: getting-started/installation.md
  - Fundamentals:
    - Command: features/command.md
    - Game Event: features/game-event.md
    - Variable: features/variable.md

  
# Optional: Add extensions for better rendering
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - toc:
     permalink: true
