site_name: SOAR
# site_url: Set this later when deploying to GitHub Pages
repo_url: https://github.com/ripandy/SOAR # <-- Add your repo URL here
repo_name: SOAR # <-- Add your repo name here (e.g., user/repo)
  # You can also use a FontAwesome icon for the repo link:
  # icon:
  #  repo: fontawesome/brands/github

copyright: 'Copyright &copy; 2025 Ripandy Adha'

theme:
  name: material
  favicon: assets/icons/SOAR_icon64.png
  logo: assets/icons/SOAR_icon.png

  features: # Add features section for things like navigation.tabs
    # - navigation.tabs # Uncomment if you want top-level navigation as tabs
    - content.code.copy
    - content.code.select
  
  font:
    text: 'Lato'
    code: 'Fira Code'
    
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Overview: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
  - Core Concepts:
    - Architectural Principles: concepts/architecture.md
    - R3 Integration: concepts/r3-integration.md
  - Guides:
    - SOAR's Lifecycle: guides/soar-lifecycle.md
    - Creating Custom Assets: guides/creating-custom-assets.md
    - Testing with SOAR: guides/testing-with-soar.md
  - Features:
    - Command: features/command.md
    - GameEvent: features/game-event.md
    - Variable: features/variable.md
    - Collection: features/collection.md
    - Transaction: features/transaction.md
    - Base Classes: features/base-class.md
    - UnityEventBinder: features/unity-event-binder.md
    - Jsonable Extension: features/jsonable-extension.md 
  - Troubleshooting & FAQ: troubleshooting.md

  
# Optional: Add extensions for better rendering
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - toc:
     permalink: true
